---
  functional:
    - Сайт должен быть совместим с последними версиями браузеров

  non-functional:
    - Сайт должен быть удобным на мобильном устройстве
    - Сайт должен быть безопасным и защищать данные пользователя
    -  Сайт должен быть способен обрабатывать большое количество трафика
        (например, 1000 одновременных пользователей)
  implicit:
    - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы


